
/**
 * psIMU calibration header. Automatically generated by psIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

accel_bias[0] = -4;
accel_bias[1] = 5;
accel_bias[2] = 17;
accel_scale[0] = 4002.019235;
accel_scale[1] = 4118.470025;
accel_scale[2] = 4098.744694;

mag_bias[0] = 671;
mag_bias[1] = 150;
mag_bias[2] = 1099;
mag_scale[0] = 399.192775;
mag_scale[1] = 422.483220;
mag_scale[2] = 403.908229;
