
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

accel_bias[0] = -248;
accel_bias[1] = -331;
accel_bias[2]= 113;
accel_scale[0] = 3850.903859;
accel_scale[1] = 4175.782420;
accel_scale[2] = 4047.695331;

mag_bias[0] = -71;
mag_bias[1] = -48;
mag_bias[2] = 351;
mag_scale[0] = 373.164236;
mag_scale[1] = 418.683392;
mag_scale[2] = 393.299168;
