
/**
 * psIMU calibration header. Automatically generated by psIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

accel_bias[0] = 27;
accel_bias[1] = 7;
accel_bias[2] = 30;
accel_scale[0] = 3970.513823;
accel_scale[1] = 4138.525234;
accel_scale[2] = 4095.441771;

mag_bias[0] = 681;
mag_bias[1] = 157;
mag_bias[2] = 1097;
mag_scale[0] = 451.613509;
mag_scale[1] = 472.882480;
mag_scale[2] = 463.277831;
